@apiUrl = http://localhost:3030/boards
#@apiUrl = https://notes-fredde-23.azurewebsites.net/users
@token = {{$dotenv TOKEN}}

# Sample all boards from user GET
###
GET {{apiUrl}}
Authorization: Bearer {{token}}

# Sample board creation POST
###
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "williams maldingboard"
}

###
#Sample board deletion
DELETE {{apiUrl}}/
Authorization: Bearer {{token}}