@apiUrl = http://localhost:3030/notes
#@apiUrl = https://notes-fredde-23.azurewebsites.net/users
@token = {{$dotenv TOKEN}}

###
GET {{apiUrl}}/651ac474b07be475f75afee7
Authorization: Bearer {{token}}

### 
POST {{apiUrl}}/651abcf1de52a7d510892394
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "niklas maldingtext"
}

### 
PATCH {{apiUrl}}/651c4404d103b9823a84f88d
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "williams patched maldingtext v2"
}

###
DELETE {{apiUrl}}/651c7b528aa849752ba02df3
Content-Type: application/json
Authorization: Bearer {{token}}

###