@apiUrl = http://localhost:3030/users
#@apiUrl = https://notes-fredde-23.azurewebsites.net/users
@token = {{$dotenv TOKEN}}

###
GET {{apiUrl}}
Authorization: Bearer {{token}}


###
GET {{apiUrl}}
Authorization: Bearer {{token}}

### Logga in på /login  <--- Here
POST {{apiUrl}}/login
Content-Type: application/json

{
    "email": "william@foo.baz",
    "password": "Password1234"
}

### skapa ny användare
POST {{apiUrl}}
Content-Type: application/json

{
    "email": "william@foo.baz",
    "password": "Password1234"
}

### 
PATCH {{apiUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "password": "Password123"
}

###
DELETE {{apiUrl}}/650d7698914bb30bb07b1863
Authorization: Bearer {{token}}

###